server:
  port: 8086

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: project1
  sql:
    init:
        mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/mydb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        envers:
          store_data_at_delete: true
          global_with_modified_flag: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 25MB
  mail:
    host: smtp.ethereal.email
    port: 587
    username: alfredo.schmeler26@ethereal.email
    password: f69EFnCBdY9Zt3wEM5
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
#  cache:
#    type: caffeine
#   ehcache:
#      config: classpath:ehcache3.xml


# swagger custom config
springdoc:
  api-docs:
      path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  group-configs:
    - group: v1
      paths-to-match: /api/v1/**
    - group: v2
      paths-to-match: /api/v2/**


logging:
  level:
    org:
      springframework:
        beans: info
        web: info
        context: info
        core: info
      hibernate:
        SQL: DEBUG

app:
  allowedorigin: "*"
  storagefolder: C:/tempBidon

management:
  server:
    port: 8087
  endpoints:
    web.exposure.include: '*'
    prometheus.enabled: true

